### ISSUE TITLE
Upgrade framework to use latest JTAppleCalendar 7.1.4 (current version: 6.0)

### ISSUE THREAD

**Issue by CeceXX** [orazz/CalendarPopUp#14]

**Comment by orazz** [comment]
Why do u want to upgrade this if it works in version(6.0)? or there is

**Comment by CeceXX** [comment]
lots of bugs & improvements in the latest version I believe

**Comment by CeceXX** [comment]
plus I'm using JTAppleCalendar 7.1.4 in my app already

**Comment by orazz** [comment]
I'm working on it

**Comment by CeceXX** [comment]
Nice cheers.

**Comment by orazz** [comment]
Done!
