### ISSUE TITLE
The days of the week are not matching

### ISSUE THREAD

**Issue by di1606** [orazz/CalendarPopUp#16]
HI,
When the calendar is displayed, the days of the week at the bottom of the day view select do not match. Do you know how to fix this little bug?

<img width="272" alt="capture d ecran 2018-03-05 a 20 20 30" src="https://user-images.githubusercontent.com/27860198/36995013-30caaeac-20b3-11e8-8ffb-1853ccd6cae4.png">

Thank you

**Comment by orazz** [comment]
CalendarPopUp.swift
configureCalendar function set parameters like this:
```
let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: testCalendar,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfGrid,
                                                 firstDayOfWeek: DaysOfWeek.monday)
```

**Comment by di1606** [comment]
thank.
