### ISSUE TITLE
The UI do mess up after pod update?

### ISSUE THREAD

**Issue by kevinlee85** [orazz/CalendarPopUp#4]
My Calendar is messed up as below snapshot after I did pod update and update my Xcode to 8.3?
Do you have any idea about this issue?
![screen shot 2017-04-06 at 2 36 00 pm](https://cloud.githubusercontent.com/assets/6616311/24740970/6513227c-1ad6-11e7-97f7-038512dc8cc4.png)

**Comment by orazz** [comment]
use JTAppleCalendar v: 6, ```pod 'JTAppleCalendar', '~>6.0'```

**Comment by kevinlee85** [comment]
Oh, yes, you are right. Seems JTAppleCalendar 6.1 mess up something.

**Comment by yu629** [comment]
pod 'JTAppleCalendar', '6.0' frame is also change

**Comment by yu629** [comment]
Excuse me what reason ?
