### ISSUE TITLE
The select date in top label is one day behind the select day in Calendar? 

### ISSUE THREAD

**Issue by kevinlee85** [orazz/CalendarPopUp#6]
I have changed my Computer timezone to Los Angeles PDT one. Then launch the demo simulator.

The select date in top label is one day behind the select day in Calendar? 
![screen shot 2017-04-17 at 8 41 59 pm](https://cloud.githubusercontent.com/assets/6616311/25113797/c7194d44-23ae-11e7-86c0-815903f4d61a.png)

**Comment by kevinlee85** [comment]
Finally, I found one solution, User should upgrade the library to 6.1.

**Comment by ArvindPrakashJoshi** [comment]
It is occurred even you can view this in gif file of readme. 
![screenshot 2018-12-19 at 3 57 12 pm](https://user-images.githubusercontent.com/13146321/50214657-d553bc80-03a6-11e9-85ff-dcc60b0f1371.png)
