### ISSUE TITLE
Minimum date

### ISSUE THREAD

**Issue by abhiiosraz** [orazz/CalendarPopUp#9]
How can i set minimum date

**Comment by orazz** [comment]
https://github.com/orazz/CalendarPopUp/issues/7 See last comment.

**Comment by abhiiosraz** [comment]
I want user can select start date from today only ,

**Comment by orazz** [comment]
CellView.swift 
```private let preDateSelectable: Bool = false```

**Comment by abhiiosraz** [comment]
Thx it work
